version: '3.9'
services:
  renterd:
    image: ghcr.io/siafoundation/renterd:master
    env_file:
      - .env
    ports:
      - 9980:9980
      - 9981:9981
      - 8080:8080
    volumes:
      - ./data:/data
    restart: unless-stopped
    stop_grace_period: 5m